import React from 'react';
//import videoBg from '../videos/video.mp4'
import './MissionStyle.css'
import Map from './Map';
// import Course from './Course';


function StudentsPage(props) {
    return (
        <div className='mt-4' style={{display: "flex", paddingRight: 30}}>
            <div className="Mission" style={{width: "45%"}}>
                <div id='PricingpageDiv2'>
                    <div id="textOnImg">   </div>
                </div>
                <h1 style={{color: "black"}}>Dicover the New collection points near you!</h1>
                
                <p style={{color: "black"}}>Recycling is an essential practice that helps to reduce the amount of waste generated by humans and protect the environment. Recycling conserves natural resources and energy, reduces greenhouse gas emissions, and prevents pollution. However, for recycling to be effective, it needs to be accessible and convenient for people. That's why it's important to stay up-to-date on the new recycling collection points in your area. These new collection points can make it easier for you to recycle and ensure that your efforts to protect the environment are effective.</p>
                <p style={{color: "black"}}>
                If you're looking to recycle your waste, it's always helpful to know where your nearest collection point is. Recycling has become an essential part of our daily lives, and finding convenient locations to recycle can make it much easier for us to do our part in protecting the environment. Fortunately, many cities and towns have multiple recycling points, and with advancements in technology, it's now easier than ever to find them. By using online search tools or mobile apps, you can quickly locate nearby recycling centers and make sure your waste is disposed of in an environmentally friendly way. So don't hesitate to discover the new recycle collection points near you and start recycling your waste today !
                </p>
            </div>
        
            {/* <Course/> */}
            <Map />
        </div>
    );
}

export default StudentsPage;